### ISSUE TITLE
Kali linux 1.07 JSON error 

### ISSUE THREAD

**Issue by vecna** [vecna/trackmap#36]
from an adopters:

    root@kali:~/trackmap/trackmap-master# ./perform_analysis.py -c czechrep
    [Errno 2] No such file or directory
    You can specify your Twitter handle with -t and get mentioned by @trackography_
     ࿓  Importing media list:
     ࿓  Checking your network source.
    Traceback (most recent call last):
      File "./perform_analysis.py", line 1060, in <module>
        main()
      File "./perform_analysis.py", line 779, in main
        get_client_info(os.path.join(OUTPUTDIR, 'first.json'))
      File "./perform_analysis.py", line 74, in get_client_info
        json.dump(client_ip.json(), fp)
    TypeError: 'dict' object is not callable

**Comment by vecna** [comment]
good,

pip install requests -U

upgrade requests module, and works like a charm.
